project_name: apt-proxy

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      ldflags:
        - -w -s -X "github.com/soulteary/apt-proxy/cli/cli.Version={{ .Tag }}"
    id: macos
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: ["386", arm, amd64, arm64]
    goarm:
      - "7"
      - "6"

changelog:
  skip: true

dockers:

  - image_templates:
      - "soulteary/apt-proxy:linux-amd64-{{ .Tag }}"
      - "soulteary/apt-proxy:linux-amd64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goarch: amd64
    skip_push: "false"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/apt-proxy"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/apt-proxy"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-v2"

docker_manifests:
  - name_template: "soulteary/apt-proxy:{{ .Tag }}"
    image_templates:
      - "soulteary/apt-proxy:linux-amd64-{{ .Tag }}"
    skip_push: "false"

  - name_template: "soulteary/apt-proxy:latest"
    image_templates:
      - "soulteary/apt-proxy:linux-amd64-{{ .Tag }}"
    skip_push: "false"
